### ISSUE TITLE
[Bug] strange perfect whole round firetower

### ISSUE THREAD

**Issue by ghost** [Stardust-Labs-MC/Structory#6] opened 2023-07-22 16:56 UTC
### What Minecraft version(s) does this apply to?

1.20

### Project version

1.3.2

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

i aint no bug tester but ive found more bugs in stardust labs mods than cockroaches in a motel.

seems someone saved the model of the firetower on a round grass circle with air blocks around the edges  

you might wunna test your mods before publishing them, at least mark them alpha or beta instead of full release 
![image](https://github.com/Stardust-Labs-MC/Structory/assets/86117177/33ec4cef-5343-4baa-a2b6-d31c669a0095)

it would be much easier if i could get unbanned from the stardust labs discord to report bugs there instead of searching for the structory github page or you could just put this page as the issue page on curseforge

**Comment by Apollounknowndev** [comment] 2023-07-22 18:20
Duplicate of #5

**Closed as not planned** 2023-12-07 17:22 UTC
Labels: bug, duplicate
